In [1]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from bs4 import BeautifulSoup
import time
import pandas as pd
# pd.set_option('display.max_columns', None) # 데이터프레임 컬럼 display

import warnings
warnings.filterwarnings('ignore') # 경고 무시

# 여자배구 모델별 결과 정확도

In [2]:
df2 = pd.read_csv('모델링데이터.csv',encoding='utf8')
df2

,Unnamed: 0,결과,홈_어웨이,팀코드,상대팀코드,홈어웨이_공격성공률_평균,홈어웨이_서브성공률_평균,홈어웨이_디그성공률_평균,홈어웨이_세트성공률_평균,홈어웨이_리시브정확도_평균,...,블로킹_평균_다섯,세트_평균_다섯,서브_평균_다섯,범실_상대전적,디그_상대전적,리시브_상대전적,공격종합_상대전적,블로킹_상대전적,세트_상대전적,서브_상대전적
0,0,0,1,3,1,0.383117,0.055065,0.831558,0.356558,0.383182,...,0.124318,0.347192,0.049483,18.617284,0.853457,0.410494,0.397284,0.134691,0.371975,0.059259
1,1,1,0,1,3,0.364675,0.045000,0.830130,0.337273,0.409286,...,0.125658,0.339421,0.048408,19.962963,0.840864,0.436049,0.337778,0.111111,0.313580,0.055556
2,2,0,1,4,5,0.370274,0.045753,0.832466,0.338356,0.410205,...,0.123277,0.332156,0.044270,17.653846,0.838846,0.395256,0.342179,0.129744,0.308590,0.042051
3,3,1,0,5,4,0.387600,0.051000,0.837933,0.352200,0.392133,...,0.140152,0.358676,0.050566,17.256410,0.842949,0.422051,0.391795,0.169615,0.360385,0.059487
4,4,1,0,0,2,0.406039,0.048182,0.828377,0.376299,0.410714,...,0.136446,0.376486,0.053095,19.908046,0.834713,0.434368,0.397701,0.118046,0.370575,0.053678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
943,943,0,0,1,3,0.355000,0.030000,0.825000,0.320000,0.340000,...,0.118000,0.308000,0.044000,20.000000,0.843333,0.460000,0.346667,0.103333,0.326667,0.050000
944,944,0,0,6,2,0.370000,0.035000,0.735000,0.340000,0.325000,...,0.128000,0.348000,0.040000,22.666667,0.733333,0.350000,0.386667,0.130000,0.356667,0.023333
945,945,1,1,2,6,0.375000,0.020000,0.835000,0.350000,0.350000,...,0.094000,0.336000,0.026000,21.000000,0.883333,0.503333,0.360000,0.180000,0.326667,0.066667
946,946,1,1,0,4,0.445000,0.090000,0.780000,0.425000,0.505000,...,0.130000,0.408000,0.062000,17.333333,0.800000,0.426667,0.423333,0.163333,0.400000,0.056667
947,947,0,0,4,0,0.455000,0.050000,0.830000,0.425000,0.485000,...,0.136000,0.352000,0.048000,22.000000,0.823333,0.393333,0.336667,0.116667,0.303333,0.036667

In [3]:
from sklearn.preprocessing import MinMaxScaler
data = df2.copy()
# data[['범실_평균_다섯', '디그_평균_다섯', '리시브_평균_다섯',
#        '공격종합_평균_다섯', '블로킹_평균_다섯', '세트_평균_다섯', '서브_평균_다섯', '범실_상대전적', '디그_상대전적',
#        '리시브_상대전적', '공격종합_상대전적', '블로킹_상대전적', '세트_상대전적', '서브_상대전적']] = MinMaxScaler().fit_transform(data[['범실_평균_다섯', '디그_평균_다섯', '리시브_평균_다섯',
#        '공격종합_평균_다섯', '블로킹_평균_다섯', '세트_평균_다섯', '서브_평균_다섯', '범실_상대전적', '디그_상대전적',
#        '리시브_상대전적', '공격종합_상대전적', '블로킹_상대전적', '세트_상대전적', '서브_상대전적']])
data

,Unnamed: 0,결과,홈_어웨이,팀코드,상대팀코드,홈어웨이_공격성공률_평균,홈어웨이_서브성공률_평균,홈어웨이_디그성공률_평균,홈어웨이_세트성공률_평균,홈어웨이_리시브정확도_평균,...,블로킹_평균_다섯,세트_평균_다섯,서브_평균_다섯,범실_상대전적,디그_상대전적,리시브_상대전적,공격종합_상대전적,블로킹_상대전적,세트_상대전적,서브_상대전적
0,0,0,1,3,1,0.383117,0.055065,0.831558,0.356558,0.383182,...,0.124318,0.347192,0.049483,18.617284,0.853457,0.410494,0.397284,0.134691,0.371975,0.059259
1,1,1,0,1,3,0.364675,0.045000,0.830130,0.337273,0.409286,...,0.125658,0.339421,0.048408,19.962963,0.840864,0.436049,0.337778,0.111111,0.313580,0.055556
2,2,0,1,4,5,0.370274,0.045753,0.832466,0.338356,0.410205,...,0.123277,0.332156,0.044270,17.653846,0.838846,0.395256,0.342179,0.129744,0.308590,0.042051
3,3,1,0,5,4,0.387600,0.051000,0.837933,0.352200,0.392133,...,0.140152,0.358676,0.050566,17.256410,0.842949,0.422051,0.391795,0.169615,0.360385,0.059487
4,4,1,0,0,2,0.406039,0.048182,0.828377,0.376299,0.410714,...,0.136446,0.376486,0.053095,19.908046,0.834713,0.434368,0.397701,0.118046,0.370575,0.053678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
943,943,0,0,1,3,0.355000,0.030000,0.825000,0.320000,0.340000,...,0.118000,0.308000,0.044000,20.000000,0.843333,0.460000,0.346667,0.103333,0.326667,0.050000
944,944,0,0,6,2,0.370000,0.035000,0.735000,0.340000,0.325000,...,0.128000,0.348000,0.040000,22.666667,0.733333,0.350000,0.386667,0.130000,0.356667,0.023333
945,945,1,1,2,6,0.375000,0.020000,0.835000,0.350000,0.350000,...,0.094000,0.336000,0.026000,21.000000,0.883333,0.503333,0.360000,0.180000,0.326667,0.066667
946,946,1,1,0,4,0.445000,0.090000,0.780000,0.425000,0.505000,...,0.130000,0.408000,0.062000,17.333333,0.800000,0.426667,0.423333,0.163333,0.400000,0.056667
947,947,0,0,4,0,0.455000,0.050000,0.830000,0.425000,0.485000,...,0.136000,0.352000,0.048000,22.000000,0.823333,0.393333,0.336667,0.116667,0.303333,0.036667

In [4]:
# X, Y 선택
features = ['홈_어웨이', '팀코드', '상대팀코드', '범실_평균_다섯', '디그_평균_다섯', '리시브_평균_다섯',
        '블로킹_평균_다섯', '세트_평균_다섯', '서브_평균_다섯', '범실_상대전적', '디그_상대전적',
       '공격종합_상대전적', '블로킹_상대전적', '세트_상대전적', '서브_상대전적']

X = data.loc[:436,features]
y = data.loc[:436,'결과']

In [5]:
# 학습, 검증 데이터 분리
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(
    X, y, 
#     stratify=Y,
    test_size=0.3,
    random_state=0)

In [6]:
# LogisticRegression 알고리즘
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression().fit(X_train, Y_train)
lr.score(X_train, Y_train), lr.score(X_test, Y_test)

(0.5770491803278689, 0.553030303030303)

In [7]:
# DecisionTree 알고리즘
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(max_depth=10).fit(X_train, Y_train)
dtc.score(X_train, Y_train), dtc.score(X_test, Y_test)

(0.9245901639344263, 0.5606060606060606)

In [8]:
dtc.get_depth()

10

In [9]:
from sklearn.ensemble import RandomForestClassifier
RFC = RandomForestClassifier(max_depth=5).fit(X_train,Y_train)
RFC.score(X_train,Y_train), RFC.score(X_test,Y_test)

(0.8754098360655738, 0.5909090909090909)

In [10]:
a = ['GS칼텍스', '흥국생명', '한국도로공사', "IBK기업은행", "KGC인삼공사", "현대건설", "페퍼저축은행"]
b=list(range(0,7))
dic = dict(zip(b,a))

In [11]:
for i in range(0,7):
    print(dic[i],'팀의 예측성공율 : ',RFC.score(data[data['팀코드']==i].loc[436:,features],data[data['팀코드']==i].loc[436:,'결과']))

GS칼텍스 팀의 예측성공율 :  0.6707317073170732
흥국생명 팀의 예측성공율 :  0.5833333333333334
한국도로공사 팀의 예측성공율 :  0.5641025641025641
IBK기업은행 팀의 예측성공율 :  0.6463414634146342
KGC인삼공사 팀의 예측성공율 :  0.5256410256410257
현대건설 팀의 예측성공율 :  0.44871794871794873
페퍼저축은행 팀의 예측성공율 :  0.9

In [12]:
결과예측 = data.loc[436:,:]

결과예측['예측'] = RFC.predict(data.loc[436:,features])
결과예측['팀명']= 결과예측['팀코드'].replace(dic)
결과예측['상대팀']= 결과예측['상대팀코드'].replace(dic)
결과예측[['팀명','상대팀','결과','예측']].head(20)

          팀명      상대팀  결과  예측
436  IBK기업은행   한국도로공사   0   0
437   한국도로공사  IBK기업은행   1   0
438    GS칼텍스  KGC인삼공사   0   1
439  KGC인삼공사    GS칼텍스   1   0
440   한국도로공사     흥국생명   1   0
441     흥국생명   한국도로공사   0   1
442  IBK기업은행  KGC인삼공사   0   0
443  KGC인삼공사  IBK기업은행   1   0
444    GS칼텍스     현대건설   1   1
445     현대건설    GS칼텍스   0   1
446  KGC인삼공사     흥국생명   0   0
447     흥국생명  KGC인삼공사   1   1
448   한국도로공사     현대건설   0   0
449     현대건설   한국도로공사   1   0
450  IBK기업은행  KGC인삼공사   1   0
451  KGC인삼공사  IBK기업은행   0   0
452    GS칼텍스   한국도로공사   0   0
453   한국도로공사    GS칼텍스   1   0
454     현대건설     흥국생명   0   0
455     흥국생명     현대건설   1   1

In [13]:
from xgboost import XGBClassifier as xgb

Xgb = xgb(learning_rate=0.04)
Xgb.fit(X_train,Y_train)
Xgb.score(X_train,Y_train), Xgb.score(X_test,Y_test)

(0.9868852459016394, 0.5075757575757576)

In [14]:
from lightgbm import LGBMClassifier

light = LGBMClassifier(max_depth=4)
light.fit(X_train,Y_train)
light.score(X_train,Y_train),light.score(X_test,Y_test)

(0.9672131147540983, 0.5984848484848485)

# 남자배구 모델별 결과 정확도

In [15]:
남자배구 = pd.read_csv('남자배구모델데이터.csv',encoding='utf8')

In [16]:
남자배구.columns

Index(['Unnamed: 0', '결과', '홈_어웨이', '팀코드', '상대팀코드', '홈어웨이_공격성공률_평균',
       '홈어웨이_서브성공률_평균', '홈어웨이_디그성공률_평균', '홈어웨이_세트성공률_평균', '홈어웨이_리시브정확도_평균',
       '홈어웨이_블로킹성공률_평균', '홈어웨이_범실_평균', '범실_평균_다섯', '디그_평균_다섯', '리시브_평균_다섯',
       '공격종합_평균_다섯', '블로킹_평균_다섯', '세트_평균_다섯', '서브_평균_다섯', '범실_상대전적', '디그_상대전적',
       '리시브_상대전적', '공격종합_상대전적', '블로킹_상대전적', '세트_상대전적', '서브_상대전적'],
      dtype='object')

In [17]:
from sklearn.preprocessing import MinMaxScaler
data = 남자배구.iloc[:1152,:].copy()
# data[['범실_평균_다섯', '디그_평균_다섯', '리시브_평균_다섯',
#        '공격종합_평균_다섯', '블로킹_평균_다섯', '세트_평균_다섯', '서브_평균_다섯', '범실_상대전적', '디그_상대전적',
#        '리시브_상대전적', '공격종합_상대전적', '블로킹_상대전적', '세트_상대전적', '서브_상대전적']] = MinMaxScaler().fit_transform(data[['범실_평균_다섯', '디그_평균_다섯', '리시브_평균_다섯',
#        '공격종합_평균_다섯', '블로킹_평균_다섯', '세트_평균_다섯', '서브_평균_다섯', '범실_상대전적', '디그_상대전적',
#        '리시브_상대전적', '공격종합_상대전적', '블로킹_상대전적', '세트_상대전적', '서브_상대전적']])
data

,Unnamed: 0,결과,홈_어웨이,팀코드,상대팀코드,홈어웨이_공격성공률_평균,홈어웨이_서브성공률_평균,홈어웨이_디그성공률_평균,홈어웨이_세트성공률_평균,홈어웨이_리시브정확도_평균,...,블로킹_평균_다섯,세트_평균_다섯,서브_평균_다섯,범실_상대전적,디그_상대전적,리시브_상대전적,공격종합_상대전적,블로킹_상대전적,세트_상대전적,서브_상대전적
0,0,0,0,0,1,0.535056,0.064157,0.744775,0.510169,0.472079,...,0.191537,0.505966,0.066802,24.218750,0.734375,0.498646,0.520729,0.173854,0.500208,0.067083
1,1,1,1,1,0,0.527849,0.050581,0.741802,0.491279,0.483663,...,0.201561,0.484971,0.051434,21.031250,0.750833,0.516979,0.531458,0.209896,0.478750,0.053646
2,2,1,1,2,3,0.518059,0.066471,0.729647,0.493882,0.415235,...,0.168108,0.479518,0.063831,24.930556,0.755972,0.441806,0.508889,0.196111,0.473333,0.083056
3,3,0,0,3,2,0.522439,0.050549,0.748963,0.484268,0.431341,...,0.181976,0.484578,0.049133,23.388889,0.762917,0.532083,0.555833,0.207778,0.517917,0.043194
4,4,1,1,4,5,0.506463,0.063598,0.749329,0.476098,0.432378,...,0.189617,0.481485,0.065234,24.820513,0.731538,0.510897,0.494744,0.176154,0.445000,0.059359
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1147,1147,1,1,6,3,0.530000,0.030000,0.795000,0.510000,0.485000,...,0.180000,0.510000,0.062000,19.666667,0.756667,0.466667,0.526667,0.120000,0.500000,0.066667
1148,1148,1,1,0,1,0.515000,0.095000,0.770000,0.485000,0.425000,...,0.194000,0.540000,0.072000,24.333333,0.733333,0.466667,0.510000,0.190000,0.500000,0.056667
1149,1149,0,0,1,0,0.480000,0.020000,0.675000,0.430000,0.470000,...,0.184000,0.496000,0.020000,23.333333,0.723333,0.473333,0.493333,0.176667,0.476667,0.023333
1150,1150,1,1,2,4,0.540000,0.080000,0.620000,0.495000,0.375000,...,0.164000,0.494000,0.090000,24.666667,0.790000,0.436667,0.440000,0.213333,0.336667,0.053333
1151,1151,0,0,4,2,0.480000,0.030000,0.760000,0.475000,0.400000,...,0.152000,0.490000,0.046000,18.333333,0.786667,0.480000,0.506667,0.126667,0.443333,0.036667

In [18]:
data.columns

Index(['Unnamed: 0', '결과', '홈_어웨이', '팀코드', '상대팀코드', '홈어웨이_공격성공률_평균',
       '홈어웨이_서브성공률_평균', '홈어웨이_디그성공률_평균', '홈어웨이_세트성공률_평균', '홈어웨이_리시브정확도_평균',
       '홈어웨이_블로킹성공률_평균', '홈어웨이_범실_평균', '범실_평균_다섯', '디그_평균_다섯', '리시브_평균_다섯',
       '공격종합_평균_다섯', '블로킹_평균_다섯', '세트_평균_다섯', '서브_평균_다섯', '범실_상대전적', '디그_상대전적',
       '리시브_상대전적', '공격종합_상대전적', '블로킹_상대전적', '세트_상대전적', '서브_상대전적'],
      dtype='object')

In [19]:
# X, Y 선택
features = ['홈_어웨이','팀코드', '상대팀코드', '홈어웨이_공격성공률_평균',
       '홈어웨이_서브성공률_평균', '홈어웨이_디그성공률_평균', '홈어웨이_세트성공률_평균', '홈어웨이_리시브정확도_평균',
       '홈어웨이_블로킹성공률_평균', '홈어웨이_범실_평균', '범실_평균_다섯', '디그_평균_다섯', '리시브_평균_다섯',
       '공격종합_평균_다섯', '블로킹_평균_다섯', '세트_평균_다섯', '서브_평균_다섯', '범실_상대전적', '디그_상대전적',
       '리시브_상대전적', '공격종합_상대전적', '블로킹_상대전적', '세트_상대전적', '서브_상대전적']

X = data[features]
y = data['결과']

In [20]:
# 학습, 검증 데이터 분리
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(
    X, y, 
#     stratify=Y,
    test_size=0.4
)

In [21]:
# LogisticRegression 알고리즘
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression().fit(X_train, Y_train)
lr.score(X_train, Y_train), lr.score(X_test, Y_test)

(0.5875542691751086, 0.5921908893709328)

In [22]:
# DecisionTree 알고리즘
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(max_depth=11).fit(X_train, Y_train)
dtc.score(X_train, Y_train), dtc.score(X_test, Y_test)

(0.9681620839363242, 0.5726681127982647)

In [23]:
dtc.get_depth()

11

In [24]:
from sklearn.ensemble import RandomForestClassifier
RFC = RandomForestClassifier(max_depth=3).fit(X_train,Y_train)
RFC.score(X_train,Y_train), RFC.score(X_test,Y_test)

(0.7206946454413893, 0.6247288503253796)

In [25]:
RFC.score(남자배구[남자배구['팀코드']==3].loc[1152:,features],
# 대한항공 : 0
# 현대캐피탈 : 1
# KB손해보험 : 2
# 삼성화재 : 3
# OK금융그룹 : 4
# 한국전력 : 5
# 우리카드 : 6
          남자배구[남자배구['팀코드']==3].loc[1152:,'결과'])

0.5555555555555556

In [26]:
a = ['대한항공', '현대캐피탈', 'KB손해보험', "삼성화재", "OK금융그룹", "한국전력", "우리카드"]
b=list(range(0,7))
dic = dict(zip(b,a))

In [27]:
for i in range(0,7):
    print(dic[i],'팀의 예측성공율 : ',RFC.score(남자배구[남자배구['팀코드']==i].loc[1152:,features],남자배구[남자배구['팀코드']==i].loc[1152:,'결과']))

대한항공 팀의 예측성공율 :  0.7777777777777778
현대캐피탈 팀의 예측성공율 :  0.5
KB손해보험 팀의 예측성공율 :  0.1
삼성화재 팀의 예측성공율 :  0.5555555555555556
OK금융그룹 팀의 예측성공율 :  0.7
한국전력 팀의 예측성공율 :  0.6
우리카드 팀의 예측성공율 :  0.5

In [31]:
결과예측 = 남자배구.loc[1152:,:]

결과예측['예측'] = RFC.predict(남자배구.loc[1152:,features])
결과예측['팀명']= 결과예측['팀코드'].replace(dic)
결과예측['상대팀']= 결과예측['상대팀코드'].replace(dic)
결과예측[['팀명','상대팀','결과','예측']].tail(20)

          팀명     상대팀  결과  예측
1200    삼성화재    한국전력   1   1
1201    한국전력    삼성화재   0   0
1202    대한항공   현대캐피탈   1   1
1203   현대캐피탈    대한항공   0   0
1204  KB손해보험    우리카드   1   0
1205    우리카드  KB손해보험   0   0
1206  OK금융그룹    삼성화재   1   1
1207    삼성화재  OK금융그룹   0   1
1208    우리카드    한국전력   1   0
1209    한국전력    우리카드   0   0
1210  KB손해보험   현대캐피탈   1   0
1211   현대캐피탈  KB손해보험   0   1
1212  OK금융그룹    대한항공   0   0
1213    대한항공  OK금융그룹   1   1
1214    삼성화재    우리카드   1   1
1215    우리카드    삼성화재   0   0
1216  KB손해보험    한국전력   0   1
1217    한국전력  KB손해보험   1   0
1218  OK금융그룹   현대캐피탈   1   0
1219   현대캐피탈  OK금융그룹   0   1

In [ ]:
from xgboost import XGBClassifier as xgb

Xgb = xgb()
Xgb.fit(X_train,Y_train)
Xgb.score(X_train,Y_train), Xgb.score(X_test,Y_test)

In [ ]:
from lightgbm import LGBMClassifier

light = LGBMClassifier()
light.fit(X_train,Y_train)
light.score(X_train,Y_train),light.score(X_test,Y_test)

In [ ]:
light.score(남자배구.loc[1152:,features],남자배구.loc[1152:,'결과'])